"""
The ingest → score → narrate → emit pipeline. This is the Mac-mini "brain" the launchd
job runs. It mirrors the agentec/finance pattern: deterministic Python computes
everything, then writes plain JSON that the static PWA reads (GitHub-as-DB).

End-to-end for each security (the blueprint's required "one end to end flow"):
  ingest quote + fundamentals + disclosures + meetings + dividends + ownership
  → score (deterministic Growth/Stability/Dividend)
  → enrich disclosures + run AI analysis (narration only; numbers stay deterministic)
  → emit data/stocks/<SYMBOL>.json + a compact card into data/universe.json

Plus market-wide files: indices, events strip, commodities, global events, and meta
(disclaimers, market status, source registry).
"""
from __future__ import annotations

import json
import os
from datetime import datetime, timezone, timedelta
from pathlib import Path

from .registry import load_universe, Security
from .scoring import score_all
from .factors import factor_meta
from .ai.narrate import enrich_disclosure, analyze_stock, compute_signals
from .adapters.mock import MockProvider
from .adapters.exchanges import ExchangeProvider
from .adapters.livescrape import LiveScrapeProvider
from .adapters.fundamentals_store import FundamentalsStore
from .adapters.gdelt import GdeltProvider
from .adapters.worldbank import WorldBankProvider

UTC = timezone.utc
DATA_VERSION = 1


def _now() -> datetime:
    return datetime.now(UTC)


def _iso(dt: datetime | None = None) -> str:
    return (dt or _now()).replace(microsecond=0).isoformat()


DISCLAIMERS = {
    "general": ("UAE Stocks Intelligence is an information and research-support tool. It is "
                "NOT investment advice, a recommendation, or a solicitation. Data may be "
                "delayed and is shown for demonstration unless a licensed feed is connected."),
    "ai": ("AI Analysis is app-generated research support produced by an explainable model. "
           "House scores are computed by a deterministic engine, not by the AI. This is not "
           "personalised financial advice. Under the UAE SCA framework, only registered "
           "parties may give financial recommendations."),
    "arabic": ("Where a document's source language is Arabic, the Arabic text is the official "
               "version; English is an app-generated translation provided for convenience."),
    "data": ("Official exchange and issuer sources rank first; media second; opinion last. "
             "Every item carries its source and timestamp. Real-time/redistributed market "
             "data requires a licensed agreement with the exchange or an authorised vendor."),
}


def _market_status(now: datetime) -> dict:
    # UAE markets trade Mon–Fri. (Demo logic; a real circular feed would override.)
    weekday = now.weekday()  # Mon=0 .. Sun=6
    is_weekend = weekday >= 5
    return {
        "state": "closed" if is_weekend else "open",
        "label_en": "Markets closed (weekend)" if is_weekend else "Markets open",
        "label_ar": "السوق مغلق (عطلة)" if is_weekend else "السوق مفتوح",
        "note_en": "Showing latest available data.",
        "circulars": [],
        "as_of": _iso(now),
    }


def build_launch_readiness(provider: str, counts: dict, generated_at: str | None = None) -> dict:
    allow_live = os.environ.get("UAE_ALLOW_LIVE_EXCHANGE", "0") == "1"
    checks = [
        {
            "id": "demo_and_provenance",
            "label": "Demo/live data labelling",
            "status": "pass",
            "owner": "app",
            "evidence": (
                f"Current provider={provider}; quote rows carry provenance and "
                "data_quality badges. Counts are generated by the Python brain."
            ),
            "next": "Keep the visible banner and per-row data-quality badges on every public build.",
        },
        {
            "id": "live_exchange_gate",
            "label": "ADX/DFM live refresh gate",
            "status": "review" if allow_live else "pass",
            "owner": "Khalid",
            "evidence": (
                "UAE_ALLOW_LIVE_EXCHANGE=1; the scraper can run if invoked."
                if allow_live else
                "UAE_ALLOW_LIVE_EXCHANGE is not set; unattended scraping/deploy exits safely."
            ),
            "next": "Enable only after the data-rights/licensing posture is explicitly approved.",
        },
        {
            "id": "data_rights",
            "label": "Market-data redistribution rights",
            "status": "blocked",
            "owner": "Khalid + vendor/exchange",
            "evidence": "ADX/DFM endpoint map exists, but redistribution rights are not confirmed.",
            "next": "Choose licensed feed/vendor or get explicit delayed-source terms clearance.",
        },
        {
            "id": "sca_signoff",
            "label": "SCA recommendation-risk sign-off",
            "status": "blocked",
            "owner": "Khalid + UAE securities counsel",
            "evidence": "App is framed as research support, but SCA Resolution 10/R.M-2025 needs legal sign-off.",
            "next": "Pull final SCA text and approve the exact public wording before real launch.",
        },
        {
            "id": "personal_holdings",
            "label": "Personal holdings connection",
            "status": "pass",
            "owner": "app",
            "evidence": "No personal holdings or portfolio data is connected in this repo.",
            "next": "Connect UAE Portfolio Watcher only after explicit approval.",
        },
        {
            "id": "public_scratch_files",
            "label": "Internal scrape scratch files",
            "status": "pass",
            "owner": "app",
            "evidence": "tools/build.sh strips live_quotes.json and symbols.json from web/data and dist/data.",
            "next": "Keep scraper scratch ignored and out of public bundles.",
        },
        {
            "id": "llm_boundary",
            "label": "LLM boundary",
            "status": "pass",
            "owner": "app",
            "evidence": "Scores, stance and confidence are deterministic; AI provider only narrates.",
            "next": "Do not let an LLM produce prices, scores, or recommendations.",
        },
    ]
    status_counts: dict[str, int] = {}
    for check in checks:
        status_counts[check["status"]] = status_counts.get(check["status"], 0) + 1
    return {
        "generated_at": generated_at or _iso(),
        "mode": provider,
        "counts": counts,
        "summary": {
            "demo_status": "safe",
            "real_launch_status": "blocked",
            "blocking_reason": "Market-data redistribution rights and SCA sign-off are not complete.",
            "live_exchange_refresh_enabled": allow_live,
            "next_decision": "Licensed feed/vendor vs approved delayed-source launch posture.",
        },
        "status_counts": status_counts,
        "checks": checks,
    }


def _business_summary(sec: Security) -> tuple[str, str]:
    arc = {
        "bank": "a UAE bank offering corporate, retail and Islamic financial services",
        "developer": "a UAE real-estate developer building and managing residential and commercial property",
        "utility": "a UAE utility providing power, water or cooling infrastructure",
        "energy": "a UAE energy company across the oil, gas and downstream value chain",
        "petrochem": "a UAE petrochemicals producer",
        "fertilizer": "a UAE fertiliser and ammonia producer",
        "holding": "a UAE diversified holding company with interests across multiple sectors",
        "toll": "a UAE operator of toll-road / parking infrastructure with recurring usage revenue",
        "logistics": "a UAE logistics and transport operator",
        "ports": "a UAE ports, terminals and trade-enabling logistics group",
        "aviation": "a UAE airline",
        "shipping": "a UAE shipping and maritime logistics operator",
        "consumer": "a UAE consumer / food-services business",
        "healthcare": "a UAE healthcare provider",
        "telecom": "a UAE telecom and digital-services operator",
        "tech": "a UAE technology company",
        "investment": "a UAE investment and financial-services firm",
        "insurance": "a UAE insurer",
        "fuel_retail": "a UAE fuel-retail and convenience operator",
        "oil_services": "a UAE oilfield-services provider",
        "mobility": "a UAE mobility and taxi operator",
        "industrials": "a UAE industrials / materials company (steel, construction, marine works)",
    }.get(sec.archetype, "a UAE-listed company")
    en = f"{sec.name_en} is {arc}, listed on {sec.exchange} in the {sec.sector} sector."
    ar = f"{sec.name_ar} شركة مدرجة في {('سوق أبوظبي' if sec.exchange=='ADX' else 'سوق دبي المالي')} ضمن قطاع {sec.sector}."
    return en, ar


def _financial_trends(quote, fundamentals) -> dict:
    """Deterministic multi-year trend reconstruction from the demo quote + fundamentals.
    Tagged demo. Gives the Financials tab real shapes to render."""
    years = [(_now().year - i) for i in range(4, -1, -1)]  # last 5 years incl current
    mcap = quote.market_cap if quote and quote.market_cap else 1.0e10
    rev0 = mcap * 0.35  # crude revenue proxy
    g = fundamentals.revenue_growth or 0.05
    net_margin = 0.16 + fundamentals.margin_trend
    revenue, net_income, ocf = [], [], []
    r = rev0 / ((1 + g) ** 4)
    for _ in years:
        revenue.append(round(r, -5))
        ni = r * max(0.02, net_margin)
        net_income.append(round(ni, -5))
        ocf.append(round(ni * (0.9 + fundamentals.ocf_consistency * 0.3), -5))
        r *= (1 + g)
        net_margin += fundamentals.margin_trend * 0.5
    return {
        "years": years,
        "revenue": revenue,
        "net_income": net_income,
        "operating_cash_flow": ocf,
        "ratios": {
            "net_margin": round(net_income[-1] / revenue[-1], 4) if revenue[-1] else None,
            "net_debt_to_ebitda": fundamentals.net_debt_to_ebitda,
            "current_ratio": fundamentals.current_ratio,
            "payout_ratio": fundamentals.payout_ratio,
        },
        "revenue_cagr_3y": fundamentals.revenue_cagr_3y,
        "data_quality": "demo",
    }


def _exposure_block(sec: Security, commodities: list, events: list) -> dict:
    exps = []
    for key in sec.exposure_factors:
        m = factor_meta(key)
        # find a matching commodity point if the factor maps to a WB series
        cp = next((c for c in commodities if c["series"] == m.get("wb_series")), None)
        exps.append({
            "key": key, "label_en": m["label_en"], "label_ar": m["label_ar"],
            "unit": m["unit"], "wb_series": m.get("wb_series"),
            "latest_value": cp["value"] if cp else None,
            "latest_change_pct": cp["change_pct"] if cp else None,
        })
    return {
        "exposures": exps,
        "commodities": commodities,
        "events": events[:6],
        "note": "Exposure map links this name to global drivers; commodity values from World Bank, events from GDELT (or demo).",
    }


def _impact_chip(short_signal: dict) -> str:
    return {"Bullish": "Positive", "Cautious": "Cautious", "Neutral": "Neutral"}.get(
        short_signal["stance"], "Neutral")


def _latest_catalyst(disclosures: list) -> str:
    if not disclosures:
        return "No recent disclosures"
    top = max(disclosures, key=lambda d: d.materiality)
    label = {
        "results": "Results", "board_meeting": "Board meeting", "agm_invitation": "AGM",
        "agm_resolution": "AGM resolutions", "dividend": "Dividend", "acquisition": "M&A",
        "capital_raise": "Capital raise", "governance": "Governance", "subsidiary": "Subsidiary",
    }.get(top.event_type, "Disclosure")
    return label


class Pipeline:
    def __init__(self, data_dir: Path, live: bool = False, limit: int | None = None):
        self.data_dir = data_dir
        self.live = live
        self.limit = limit
        self.mock = MockProvider()
        self.exchange = ExchangeProvider()  # routes live↔demo per env
        # quote lane: real scraped delayed quotes when live (per-symbol demo fallback), else demo
        self.quotes = LiveScrapeProvider() if live else self.exchange
        self.gdelt = GdeltProvider() if live else self.mock
        self.worldbank = WorldBankProvider() if live else self.mock
        # real reported fundamentals (Mizan agent / verified filings) override the modeled ones
        self.fundamentals_store = FundamentalsStore(data_dir)

    def run(self) -> dict:
        (self.data_dir / "stocks").mkdir(parents=True, exist_ok=True)
        universe = load_universe()
        if self.limit:
            universe = universe[: self.limit]

        commodities = [c.to_dict() for c in self.worldbank.snapshot()]
        cards = []
        all_events = []
        sectors: dict[str, list[int]] = {}

        for sec in universe:
            payload, card, events = self._process(sec, commodities)
            (self.data_dir / "stocks" / f"{sec.symbol}.json").write_text(
                json.dumps(payload, ensure_ascii=False, indent=2))
            cards.append(card)
            all_events.extend(events)
            sectors.setdefault(sec.sector, []).append(card["scores"]["headline"])

        # indices (demo aggregate); a real feed would replace these two headline numbers
        cards.sort(key=lambda c: (c["exchange"], -(c["scores"]["headline"])))
        adx_cards = [c for c in cards if c["exchange"] == "ADX"]
        dfm_cards = [c for c in cards if c["exchange"] == "DFM"]

        def _idx(cs):
            if not cs:
                return {"avg_change_pct": 0, "advancers": 0, "decliners": 0, "count": 0}
            adv = sum(1 for c in cs if c["change_pct"] > 0)
            return {
                "avg_change_pct": round(sum(c["change_pct"] for c in cs) / len(cs), 4),
                "advancers": adv, "decliners": len(cs) - adv, "count": len(cs),
            }

        # real headline index (FADGI / DFMGI) when the live scraper captured it
        live_idx = getattr(self.quotes, "indices", {}) or {}
        adx_real = live_idx.get("adx") if isinstance(live_idx.get("adx"), dict) else None
        dfm_real = live_idx.get("dfm") if isinstance(live_idx.get("dfm"), dict) else None
        indices = {
            "adx": {"name": "FADGI" if adx_real else "ADX General Index (proxy)",
                    "index_value": adx_real["value"] if adx_real else None,
                    "index_change_pct": adx_real["change_pct"] if adx_real else None,
                    **_idx(adx_cards)},
            "dfm": {"name": "DFMGI" if dfm_real else "DFM General Index (proxy)",
                    "index_value": dfm_real["value"] if dfm_real else None,
                    "index_change_pct": dfm_real["change_pct"] if dfm_real else None,
                    **_idx(dfm_cards)},
            "sectors": [
                {"sector": s, "avg_score": round(sum(v) / len(v)), "count": len(v)}
                for s, v in sorted(sectors.items())
            ],
            "data_quality": "demo" if not self.live else "mixed",
        }

        # global events strip (one macro query)
        global_events = [e.to_dict() for e in self.gdelt.global_events("UAE economy markets oil", 8)]

        all_events.sort(key=lambda e: e["date"])
        meta = {
            "generated_at": _iso(),
            "data_version": DATA_VERSION,
            "provider": "live" if self.live else "mock",
            "ai_provider": __import__("os").environ.get("UAE_AI_PROVIDER", "stub"),
            "counts": {"securities": len(universe), "events": len(all_events)},
            "market_status": _market_status(_now()),
            "disclaimers": DISCLAIMERS,
            "sources": [
                {"name": "ADX", "type": "official", "url": "https://www.adx.ae"},
                {"name": "DFM", "type": "official", "url": "https://www.dfm.ae"},
                {"name": "Nasdaq Dubai", "type": "official", "url": "https://www.nasdaqdubai.com"},
                {"name": "WAM", "type": "media", "url": "https://www.wam.ae"},
                {"name": "World Bank Commodities", "type": "official", "url": "https://www.worldbank.org/en/research/commodity-markets"},
                {"name": "GDELT", "type": "media", "url": "https://www.gdeltproject.org"},
            ],
        }
        readiness = build_launch_readiness(meta["provider"], meta["counts"], meta["generated_at"])

        # write market-wide files
        self.data_dir.joinpath("universe.json").write_text(json.dumps(cards, ensure_ascii=False, indent=2))
        self.data_dir.joinpath("indices.json").write_text(json.dumps(indices, ensure_ascii=False, indent=2))
        self.data_dir.joinpath("events.json").write_text(json.dumps(all_events, ensure_ascii=False, indent=2))
        self.data_dir.joinpath("commodities.json").write_text(json.dumps(commodities, ensure_ascii=False, indent=2))
        self.data_dir.joinpath("global_events.json").write_text(json.dumps(global_events, ensure_ascii=False, indent=2))
        self.data_dir.joinpath("launch_readiness.json").write_text(
            json.dumps(readiness, ensure_ascii=False, indent=2))
        self.data_dir.joinpath("meta.json").write_text(json.dumps(meta, ensure_ascii=False, indent=2))
        return meta

    def _process(self, sec: Security, commodities: list):
        quote = self.quotes.get_quote(sec.symbol)
        real_f = self.fundamentals_store.to_fundamentals(sec.symbol, quote.price if quote else None)
        fundamentals = real_f or self.mock.get_fundamentals(sec.symbol)
        fundamentals_real = real_f is not None
        frec = self.fundamentals_store.record(sec.symbol) if fundamentals_real else None
        scores = score_all(fundamentals, sec.archetype)
        disclosures = self.exchange.list_disclosures(sec.symbol, 12)
        disclosures = [enrich_disclosure(d) for d in disclosures]
        meetings = self.mock.meetings(sec.symbol)
        dividends = self.mock.dividends(sec.symbol)
        ownership = self.mock.get_ownership(sec.symbol)

        analysis = analyze_stock(sec, quote, scores, fundamentals, disclosures)
        signals = analysis["_signal"]

        en_sum, ar_sum = _business_summary(sec)
        # per-stock exposure events use the demo provider (fast) — live GDELT is rate-limited
        # (~1 req/5s) so we only spend it on the ONE global events strip in run(); per-stock
        # demo events are tagged demo so the provenance stays honest.
        ev_query = factor_meta(sec.exposure_factors[0])["gdelt"] if sec.exposure_factors else f"{sec.name_en}"
        sec_events = [e.to_dict() for e in self.mock.global_events(f"{ev_query} UAE", 6)]

        payload = {
            "symbol": sec.symbol, "name_en": sec.name_en, "name_ar": sec.name_ar,
            "exchange": sec.exchange, "sector": sec.sector, "archetype": sec.archetype,
            "currency": sec.currency, "isin": sec.isin,
            "quote": quote.to_dict() if quote else None,
            "scores": scores,
            "fundamentals": fundamentals.to_dict(),
            "fundamentals_source": {
                "real": fundamentals_real,
                "as_of": frec.get("as_of") if frec else None,
                "source": frec.get("source") if frec else "modeled estimate",
                "source_url": frec.get("source_url") if frec else None,
                "extractor": frec.get("extractor") if frec else None,
                "confidence": frec.get("confidence") if frec else None,
            },
            "overview": {
                "business_summary_en": en_sum, "business_summary_ar": ar_sum,
                "index_membership": [sec.exchange],
                "quick_stats": {
                    "market_cap": quote.market_cap if quote else None,
                    "volume": quote.volume if quote else None,
                    "high_52w": quote.high_52w if quote else None,
                    "low_52w": quote.low_52w if quote else None,
                    "dividend_yield": fundamentals.dividend_yield,
                },
                "top_catalysts": signals["long"]["reasons"][:3],
                "top_risks": signals["long"]["risks"][:3],
            },
            "disclosures": [d.to_dict() for d in disclosures],
            "meetings": [m.to_dict() for m in meetings],
            "dividends": [d.to_dict() for d in dividends],
            "ownership": ownership.to_dict() if ownership else None,
            "financials": _financial_trends(quote, fundamentals),
            "global_factors": _exposure_block(sec, commodities, sec_events),
            "ai_analysis": analysis,
            "generated_at": _iso(),
        }

        # compact card for the home/markets grid
        card = {
            "symbol": sec.symbol, "name_en": sec.name_en, "name_ar": sec.name_ar,
            "exchange": sec.exchange, "sector": sec.sector,
            "price": quote.price if quote else None,
            "change": quote.change if quote else None,
            "change_pct": quote.change_pct if quote else None,
            "currency": sec.currency,
            "dividend_yield": fundamentals.dividend_yield,
            "scores": {
                "growth": scores["growth"]["score"],
                "stability": scores["stability"]["score"],
                "dividend": scores["dividend"]["score"],
                "headline": scores["headline"],
            },
            "catalyst": _latest_catalyst(disclosures),
            "impact": _impact_chip(signals["short"]),
            "updated_at": _iso(),
            "data_quality": quote.prov.data_quality if quote and quote.prov else "demo",
            "fundamentals_real": fundamentals_real,
        }

        # events for the home strip
        events = []
        for m in meetings:
            if m.status == "upcoming":
                events.append({"type": m.kind, "symbol": sec.symbol, "name": sec.name_en,
                               "date": m.date, "label": f"{m.kind.upper()} — {sec.symbol}"})
        for dv in dividends:
            if dv.ex_date and dv.ex_date >= _now().date().isoformat():
                events.append({"type": "dividend", "symbol": sec.symbol, "name": sec.name_en,
                               "date": dv.ex_date, "label": f"Ex-dividend — {sec.symbol} {dv.amount} AED"})
        return payload, card, events
